[package]
license.workspace = true
name = "renamed"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
actor = { package = "aktor", path = "../../aktor", default-features = false, features = ["macros", "tokio", "wasm_browser_workers"] }
er = { workspace = true, default-features = true }
tokio = { workspace = true, features = ["macros", "rt"] }
