[workspace]
resolver = "3"
members = ["aktor", "aktor-macros"]
exclude = ["integrations"]

[workspace.package]
license = "MIT-0"
readme = "README.md"
repository = "https://github.com/Viterkim/aktor"
version = "0.0.1"
edition = "2024"
rust-version = "1.89"
publish = true

[workspace.dependencies]
proc-macro-crate = "3.5"
proc-macro2 = "1.0"
quote = "1.0"
parking_lot = "0.12"
syn = { version = "3.0", features = ["full", "visit", "visit-mut"] }
tokio = { version = "1.53.1", features = ["macros", "rt", "sync"] }
futures-util = { version = "0.3", default-features = false, features = ["std"] }

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"
