[package]
license.workspace = true
name = "aktor-wasm-proof"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[features]
default = ["clock-1m"]
clock-1m = ["embassy-time/tick-hz-1_000_000", "embassy-time-driver/tick-hz-1_000_000"]
clock-32k = ["embassy-time/tick-hz-32_768", "embassy-time-driver/tick-hz-32_768"]

[dependencies]
aktor = { workspace = true, features = ["macros", "embassy"] }
er = { workspace = true, features = ["macros"] }
embassy-sync.workspace = true
futures-util = { workspace = true, features = ["alloc", "async-await"] }

embassy-time.workspace = true
embassy-time-driver.workspace = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
embassy-time = { workspace = true, features = ["std", "generic-queue-8"] }
