[package]
license.workspace = true
name = "aktor-embassy-proof"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
aktor = { workspace = true, features = ["macros", "embassy", "embassy_cross_core"] }
er = { workspace = true, default-features = true }
embassy-time.workspace = true
embassy-sync.workspace = true

[target.'cfg(not(target_os = "none"))'.dependencies]
critical-section = { workspace = true, features = ["std"] }
embassy-executor = { workspace = true, features = ["platform-std", "executor-thread"] }
embassy-time = { workspace = true, features = ["std", "generic-queue-8"] }

[target.'cfg(target_os = "none")'.dependencies]
embassy-executor = { workspace = true, features = ["platform-cortex-m", "executor-thread"] }

[dev-dependencies]
futures-util = { workspace = true, features = ["alloc", "async-await", "std"] }

[lints]
workspace = true
